<?php

namespace BasketballBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActualListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualListRepository extends EntityRepository
{
}
