<?php

namespace BasketballBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getChangedDigit($number)
    {
        $number = str_split($number);
        if ($number[0] == 0) {
            $number[0] = '';
        }
        $number = implode('', $number);

        return $number;
    }
}
