<?php

namespace BasketballBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpecialisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialisationRepository extends EntityRepository
{
}
